
pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
                dir('project1') {
                    sh('pwd; ls ; p1.sh')
                }
            }
        }
    }
}