
pipeline {
    agent {
        label 'app-server'
    }

    stages {
        stage('Build') {
            steps {
                dir('project2') {
                    sh('bash p2.sh')
                }
            }
        }
    }
}